"""Global Aesthetics and Art Style Definitions Dictionary."""

from typing import Any

ART_STYLE_INTELLIGENCE_CATALOG: dict[str, dict[str, Any]] = {
    "swiss_alpine_rainy_village": {
        "display_name": "Swiss Alpine Rainy Village & Walking Tour",
        "origin_country": "Switzerland",
        "origin_region": "Central Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/swiss_alpine_village_v1.safetensors", "scale": 0.85, "trigger": "swiss alpine village, wet wooden chalets, rain-slicked road, waterfalls, mist"},
        "prompt_decorations": "Lauterbrunnen and Grindelwald aesthetic, traditional Swiss wooden chalets with red geranium flower boxes, wet rain-slicked road reflecting green slopes, cascading waterfalls down vertical cliffs, snow-capped peaks in mist, grazing cows, 4K walking tour POV",
        "lighting_scheme": "Soft overcast rainy daylight with glistening wet pavement reflections and ethereal mountain mist",
        "color_palette": "Deep emerald green, terracotta roof tiles, slate limestone grey, glacial white, rainy asphalt charcoal",
        "directorial_guidance": "Peaceful first-person walking tour pacing, steady forward camera glide, immersive rain and waterfall ASMR.",
        "music_style": "Peaceful ambient piano and acoustic cello with immersive binaural rainfall foley and distant waterfall roar",
    },
    "swiss_alpine_scenic_8k": {
        "display_name": "Swiss Alpine Grindelwald 8K Scenic Nature",
        "origin_country": "Switzerland",
        "origin_region": "Central Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/swiss_alpine_scenic_v1.safetensors", "scale": 0.85, "trigger": "grindelwald 8k, eiger jungfrau peaks, red swiss train, turquoise river"},
        "prompt_decorations": "Grindelwald alpine wonderland, towering snow-capped Eiger and Jungfrau peaks, arched stone viaduct bridge crossing turquoise glacial river, red Swiss alpine mountain train, rolling emerald meadows, traditional chalets, 8K travel film",
        "lighting_scheme": "Brilliant crisp high-altitude alpine sunlight under deep azure blue sky with vivid contrast",
        "color_palette": "Turquoise glacial blue, vivid alpine grass green, brilliant snow white, Swiss train crimson, azure blue",
        "directorial_guidance": "Majestic aerial drone sweeps, slow horizontal tracking shots following the mountain train, serene contemplation.",
        "music_style": "Lush cinematic neoclassical piano and orchestral strings with crisp alpine breeze and distant church bells",
    },
    "alpine_rainy_scenic_drive": {
        "display_name": "Alpine Rainy Scenic Drive & Lake Church",
        "origin_country": "Austria / Germany",
        "origin_region": "Central Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/alpine_scenic_drive_v1.safetensors", "scale": 0.85, "trigger": "rainy alpine road trip, wet asphalt, lake church, tyrolean chalets, misty mountains"},
        "prompt_decorations": "Innsbruck to Tegernsee mountain pass, wet winding alpine asphalt road glistening with taillight reflections, white historic lakeside church with red steeple on peninsula, dark-timber Tyrolean chalets on green slopes, misty jagged peaks, 4K road trip vision",
        "lighting_scheme": "Atmospheric overcast rainy mountain daylight with glistening asphalt reflections and vehicle taillight glows",
        "color_palette": "Wet asphalt charcoal, lake turquoise, church steeple crimson, deep forest pine, misty slate grey",
        "directorial_guidance": "Smooth forward vehicle tracking movement, windshield perspective, rhythmic rainfall and tire spray ambient soundscape.",
        "music_style": "Atmospheric acoustic road trip guitar with authentic binaural rain patter on windshield and gentle mountain breeze",
    },
    "greek_cycladic_coastal": {
        "display_name": "Greek Cycladic Coastal & Aegean Sea Caves",
        "origin_country": "Greece",
        "origin_region": "Southern Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/greek_aegean_coastal_v1.safetensors", "scale": 0.85, "trigger": "aegean sea caves, whitewashed cycladic village, turquoise water, wooden boat"},
        "prompt_decorations": "Milos and Santorini aesthetic, crystal-clear turquoise sea water with rippling sun caustics on white sandy seabed, whitewashed Cycladic stone cottages and sea caves with curved limestone arches, deep Aegean blue doors, lone wooden rowboat in calm bay, 4K coastal relaxation",
        "lighting_scheme": "Brilliant high-noon Mediterranean sunshine casting luminous water caustics onto white limestone cliffs",
        "color_palette": "Crystal turquoise, Aegean cobalt blue, whitewash chalk, Mediterranean sand, brilliant sky cyan",
        "directorial_guidance": "Mesmerizing water caustics, slow drift past natural stone arches, sun-drenched serene tranquility.",
        "music_style": "88 BPM Café del Mar synth chillout with warm Rhodes electric piano, deep sub-bass, filtered arpeggios, and gentle wave surf foley",
    },
    "italian_coastal_lake_como": {
        "display_name": "Italian Coastal & Lake Como Morning Coffee",
        "origin_country": "Italy",
        "origin_region": "Southern Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/italian_coastal_como_v1.safetensors", "scale": 0.85, "trigger": "lake como terrace, bellagio pastel villas, waterfront dining, sparkling blue lake"},
        "prompt_decorations": "Lake Como and Amalfi Coast aesthetic, elegant waterfront dining terrace set with white linen tablecloth, wine glasses, pink roses, seated chic Italian traveler, sun shimmering bokeh on deep blue water, historic Bellagio pastel villas against verdant hills, 4K Mediterranean vibes",
        "lighting_scheme": "Sparkling mid-morning Mediterranean sunlight creating sparkling diamond caustics on water surface",
        "color_palette": "Deep sapphire water blue, Bellagio pastel peach, terracotta orange, pure linen white, rose pink",
        "directorial_guidance": "Slow elegant pan from table setting to sun-drenched lake vistas, romantic conversational pacing, gentle acoustic ambience.",
        "music_style": "Warm Italian acoustic guitar, light accordion, and mandolin melody with gentle water ripples and cafe murmurs",
    },
    "ibiza_luxury_sunset_lounge": {
        "display_name": "Ibiza Luxury Sunset Rooftop Lounge",
        "origin_country": "Spain",
        "origin_region": "Southern Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/ibiza_luxury_lounge_v1.safetensors", "scale": 0.85, "trigger": "ibiza luxury rooftop lounge, infinity pool, sunset, candle lanterns"},
        "prompt_decorations": "ultra-luxury Balearic seaside rooftop terrace at twilight, infinity pool reflecting golden setting sun, low white daybed loungers, glass hurricane lanterns with warm flickering candles, silhouetted palm trees, calm Mediterranean sea ripples, 4K architectural digest",
        "lighting_scheme": "Golden-hour sunset horizon beam transitioning to deep violet dusk with warm interior architectural lighting and candle glows",
        "color_palette": "Sunset golden amber, deep dusk violet, pure linen white, warm teak brown, shimmering pool aqua",
        "directorial_guidance": "Slow cinematic camera drift across candle lanterns and pool reflections, sophisticated lounge atmosphere.",
        "music_style": "Sophisticated Ibiza sundown lounge with mellow saxophone accents, warm Rhodes chords, deep bassline, and sea breeze foley",
    },
    "primeval_forest_sanctuary": {
        "display_name": "Primeval Emerald Forest & Stream Relaxation",
        "origin_country": "Global Nature",
        "origin_region": "Global",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/primeval_forest_sanctuary_v1.safetensors", "scale": 0.85, "trigger": "primeval forest, mossy roots, sunbeams, crystal stream, winding trail"},
        "prompt_decorations": "primeval temperate rainforest, massive ancient moss-covered tree roots, crystal-clear babbling rocky forest stream, winding dirt walking trail, volumetric sunbeams (crepuscular rays) piercing dense emerald canopy, singing birds, peaceful nature sanctuary, 4K ultra HD",
        "lighting_scheme": "Dappled volumetric god rays filtering through deep forest mist and dense emerald green foliage",
        "color_palette": "Deep moss green, forest fern emerald, wet bark brown, crystal stream white, golden sunbeam yellow",
        "directorial_guidance": "Slow contemplative forward walk along the forest stream, immersive binaural nature ASMR.",
        "music_style": "Peaceful solo piano with high-fidelity binaural recordings of babbling rocky stream, songbirds, and gentle leaves rustling",
    },
    "tropical_thailand_karst": {
        "display_name": "Tropical Thailand Karst Wonders & Teak Chalets",
        "origin_country": "Thailand",
        "origin_region": "Southeast Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/thailand_karst_wonders_v1.safetensors", "scale": 0.85, "trigger": "thailand karst mountains, flower field, teak chalet, misty pagodas"},
        "prompt_decorations": "Chiang Mai and Krabi aesthetic, geometric blooming flower plantation with vibrant rows of magenta, crimson, purple and yellow blossoms, traditional teak chalet with steep thatched roof, palm trees, towering limestone karst peaks with misty Buddhist pagodas, 4K travel film",
        "lighting_scheme": "Vibrant tropical morning sunlight illuminating vivid multi-colored flower rows against dramatic karst shadows",
        "color_palette": "Vibrant magenta, golden marigold, emerald jungle green, limestone grey, tropical teak brown",
        "directorial_guidance": "Sweeping aerial drone shot gliding over vibrant flower fields toward mist-shrouded mountain pagodas.",
        "music_style": "Uplifting tropical cinematic travel score with traditional Thai Ranat ek xylophone, bamboo flute, and soaring strings",
    },
    "japanese_ukiyo_e": {
        "display_name": "Japanese Ukiyo-e Woodblock Print (Edo Period)",
        "origin_country": "Japan",
        "origin_region": "East Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/japanese_ukiyo_e_v1.safetensors", "scale": 0.85, "trigger": "ukiyo-e woodblock print, muted mineral pigments, washi paper, black contours"},
        "prompt_decorations": "authentic Edo period ukiyo-e woodblock print, Hokusai and Hiroshige aesthetic, handmade washi paper grain, bold black calligraphy outlines, muted indigo blue and vermilion mineral pigments",
        "lighting_scheme": "Flat diffused natural ambient light with delicate ink-wash gradations and zero artificial shadows",
        "color_palette": "Indigo blue, Prussian blue, muted vermilion, persimmon orange, rice-paper beige, sumi black",
        "directorial_guidance": "Focus on poetic seasonal transience (mono no aware), stylized ceremonial movement, contemplative pacing, and natural elements.",
        "music_style": "Traditional Japanese Gagaku with Shakuhachi bamboo flute, Koto zither, and ceremonial Taiko drum accents",
    },
    "cyberpunk_neo_tokyo": {
        "display_name": "Cyberpunk Neo-Tokyo & Neo-Seoul",
        "origin_country": "Japan / South Korea",
        "origin_region": "East Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/cyberpunk_neo_tokyo_v1.safetensors", "scale": 0.85, "trigger": "cyberpunk, glowing neon kanji, wet asphalt reflections, volumetric fog"},
        "prompt_decorations": "Blade Runner aesthetic, mega-structures, glowing cyan and magenta holographic ads, rain-slicked asphalt, cybernetic augments, anamorphic lens flares, volumetric fog",
        "lighting_scheme": "High-contrast dual-tone neon lighting (cyan and magenta) cutting through dark atmospheric smog and rain",
        "color_palette": "Electric cyan, hot magenta, deep violet, midnight obsidian, street neon amber",
        "directorial_guidance": "High-octane pacing, tech-dystopian friction, sharp punchy dialogue, sensory overload, and dramatic electronic beat drops.",
        "music_style": "128 BPM dark synthwave and electro-industrial with heavy bass pulses, arpeggiated synths, and glitch transients",
    },
    "french_impressionism": {
        "display_name": "French Impressionist Plein Air",
        "origin_country": "France",
        "origin_region": "Western Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/french_impressionism_v1.safetensors", "scale": 0.85, "trigger": "impressionist oil painting, visible brushstrokes, dappled natural sunlight"},
        "prompt_decorations": "Claude Monet and Pierre-Auguste Renoir aesthetic, thick textured oil paint impasto, visible loose energetic brushwork, dappled golden sunlight, vibrant pastel palette, soft romantic haze",
        "lighting_scheme": "Warm dappled golden-hour sunlight with soft chromatic shadows and shimmering optical reflections",
        "color_palette": "Lavender blue, emerald green, warm sunflower yellow, soft rose pink, cream white",
        "directorial_guidance": "Sensory, gentle, observational, capturing fleeting moments of natural light, leisurely Parisian cafe conversations, and pastoral beauty.",
        "music_style": "Impressionist orchestral acoustic score with Claude Debussy-inspired harp, piano, and delicate woodwinds",
    },
    "italian_baroque_chiaroscuro": {
        "display_name": "Italian Renaissance & Baroque Chiaroscuro",
        "origin_country": "Italy",
        "origin_region": "Southern Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/baroque_chiaroscuro_v1.safetensors", "scale": 0.85, "trigger": "caravaggio chiaroscuro, intense single directional key light, deep tenebrism shadows, oil glaze"},
        "prompt_decorations": "Caravaggio and Artemisia Gentileschi aesthetic, intense dramatic single-source directional candlelight, profound pitch-black tenebrism shadows, rich crimson velvet drapery, oil glaze realism",
        "lighting_scheme": "Intense directional golden key light carving out subjects against deep pitch-black tenebrism shadows",
        "color_palette": "Deep crimson, burnt umber, raw sienna, antique gold, pitch black",
        "directorial_guidance": "High emotional stakes, philosophical confrontations, operatic grandeur, dramatic pauses, and intense moral dilemma.",
        "music_style": "Vivaldi-inspired Baroque string ensemble with harpsichord, intense cello ostinato, and soaring solo violin",
    },
    "korean_kpop_cyber_glam": {
        "display_name": "Korean K-Pop High-Gloss Cyber Glam",
        "origin_country": "South Korea",
        "origin_region": "East Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/kpop_cyber_glam_v1.safetensors", "scale": 0.85, "trigger": "k-pop music video aesthetic, iridescent pastel hues, high-gloss studio lighting"},
        "prompt_decorations": "futuristic Seoul studio cyclorama, high-gloss reflective floor, iridescent pastel lavender and mint green lighting, crisp chromatic aberration, razor-sharp choreographic staging",
        "lighting_scheme": "High-key pristine beauty studio lighting with iridescent pastel edge lights and sharp specular highlights",
        "color_palette": "Iridescent pastel lilac, mint green, metallic silver, candy pink, optic white",
        "directorial_guidance": "Addictive hook lines, sudden tempo switches, multilingual English-Korean catchphrases, camera orbit transitions.",
        "music_style": "126 BPM high-energy K-Pop dance beat with 808 sub-bass, bright vocal chops, and anthemic brass drops",
    },
    "african_afrofuturism": {
        "display_name": "African Afrofuturism & Neo-Wakanda",
        "origin_country": "Nigeria / Ghana / Pan-African",
        "origin_region": "West Africa",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/african_afrofuturism_v1.safetensors", "scale": 0.85, "trigger": "afrofuturism, glowing luminescent tribal geometry, kente accents, golden body ornamentation"},
        "prompt_decorations": "glowing luminescent neon tribal patterns on warm dark skin, metallic gold and bronze neck chokers, avant-garde Ankara wax print streetwear, vibrant cobalt blue and sunset amber hues",
        "lighting_scheme": "Golden-hour sunset warmth fused with glowing bioluminescent cybernetic patterns on rich dark skin",
        "color_palette": "Sunburst gold, cobalt blue, royal purple, luminous cyan, rich ebony",
        "directorial_guidance": "Reclaiming historical greatness through visionary technology, ancestral wisdom meeting space-age innovation, rhythmic call-and-response.",
        "music_style": "112 BPM modern Afrobeats fusion with log-drum Amapiano bassline, talking drums, and infectious horn section",
    },
    "mexican_muralism_magical_realism": {
        "display_name": "Mexican Muralism & Magical Realism",
        "origin_country": "Mexico",
        "origin_region": "Latin America",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/mexican_muralism_v1.safetensors", "scale": 0.85, "trigger": "mexican muralism, diego rivera style, vibrant marigold yellows, cobalt blue, bold expressive strokes"},
        "prompt_decorations": "Diego Rivera and Frida Kahlo mural aesthetic, saturated marigold orange, terracotta, and deep cobalt blue, bold sculptural figures, floating cempasúchil petals, magical realism atmosphere",
        "lighting_scheme": "High-noon brilliant Mexican sunlight with vivid warm terracotta warmth and rich saturated shadows",
        "color_palette": "Cempasúchil marigold orange, cobalt blue, terracotta red, jade green, sun yellow",
        "directorial_guidance": "Passionate storytelling steeped in folklore, ancestral connection, colorful humor, and dramatic emotional revelations.",
        "music_style": "Passionate Mexican Son Jarocho with energetic jarana guitars, harp, and celebratory trumpet flourishes",
    },
    "nordic_noir_minimalism": {
        "display_name": "Nordic Noir & Scandinavian Minimalism",
        "origin_country": "Sweden / Norway / Iceland",
        "origin_region": "Northern Europe",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/nordic_noir_v1.safetensors", "scale": 0.85, "trigger": "nordic noir, desaturated cool blue slate tones, mist fjords, architectural minimalism"},
        "prompt_decorations": "cinematic desaturated slate grey and cold fjord blue tones, clean Scandinavian architectural geometry, low-hanging arctic mist, dramatic overcast diffused lighting",
        "lighting_scheme": "Soft overcast arctic daylight with cold desaturated tones and pinpoint warm amber interior glows",
        "color_palette": "Slate grey, fjord cold blue, arctic white, charcoal black, warm amber accent",
        "directorial_guidance": "Understated psychological tension, dry minimalist wit, lingering silences, and stark realism.",
        "music_style": "Atmospheric Nordic ambient strings with bowed cello, cold synth drones, and distant acoustic piano",
    },
    "indian_mughal_miniature": {
        "display_name": "Indian Mughal & Rajasthani Miniature Art",
        "origin_country": "India",
        "origin_region": "South Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/mughal_miniature_v1.safetensors", "scale": 0.85, "trigger": "mughal miniature painting, intricate gold leaf illumination, ornate border arabesque"},
        "prompt_decorations": "exquisite Mughal court miniature painting, ultra-detailed gold leaf illumination, ornate floral arabesque borders, lapis lazuli and saffron tempera paint, stylized imperial pavilions",
        "lighting_scheme": "Even courtly miniature illumination with shimmering 24k gold leaf highlights and zero heavy shadows",
        "color_palette": "Lapis lazuli blue, saffron orange, emerald green, ruby red, genuine gold leaf",
        "directorial_guidance": "Poetic Urdu/Hindi couplets (shayari), royal court intrigue, high etiquette (tehzeeb), and opulent visual metaphors.",
        "music_style": "Classical Hindustani court music with acoustic sitar, surbahar, and delicate tabla Bols",
    },
    "retro_80s_synthwave": {
        "display_name": "Retro 80s Synthwave & Neon Outrun",
        "origin_country": "United States",
        "origin_region": "North America",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/retro_synthwave_outrun_v1.safetensors", "scale": 0.85, "trigger": "80s synthwave, glowing wireframe grid, magenta sunset gradient, chrome reflections"},
        "prompt_decorations": "1980s retro-futuristic Outrun aesthetic, infinite wireframe perspective grid, giant setting magenta and orange sun, chrome text reflections, palm tree silhouettes",
        "lighting_scheme": "Blinding sunset backlighting with intense magenta-orange horizon gradient and dark silhouetted foregrounds",
        "color_palette": "Hot magenta, electric purple, neon cyan, sunset orange, chrome silver",
        "directorial_guidance": "Nostalgic, high-speed thrill, nighttime highway philosophy, retro-technological optimism, and punchy one-liners.",
        "music_style": "120 BPM nostalgic 80s synthwave with analog Roland Juno-106 pads, gated snare drums, and arpeggiated basslines",
    },
    "indian_vibrant_4k": {
        "display_name": "Indian 4K Cinematic Heritage & Cultural Wonders",
        "origin_country": "India",
        "origin_region": "South Asia",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/indian_heritage_4k_v1.safetensors", "scale": 0.85, "trigger": "india in 4k, taj mahal, rajasthan palaces, varanasi ghats, golden hour"},
        "prompt_decorations": "India in 4K travel documentary aesthetic, monumental Mughal and Rajput marble architecture, Varanasi Ganga ghats, ornate carved sandstone archways, vibrant textiles, golden hour sun mist, 4K cinematic drone cinematography",
        "lighting_scheme": "Warm golden-hour sunlight with atmospheric haze, dramatic volumetric rays illuminating historic carved stone",
        "color_palette": "Vibrant saffron orange, deep terracotta red, royal peacock blue, shimmering gold, emerald green",
        "directorial_guidance": "Majestic drone aerials, smooth low-angle tracking shots through ancient courtyards, culturally authentic awe.",
        "music_style": "Cinematic Indian classical fusion featuring acoustic sitar, bansuri flute, tabla rhythms, and soaring orchestral swells",
        "architecture_style": "Intricate Mughal marble domes, Rajput carved sandstone palaces, ancient stepwells, and towering Dravidian temple gopurams",
    },
    "modern_architectural_minimalism": {
        "display_name": "Modern Architectural Grandeur & Contemporary Metropolis",
        "origin_country": "Global Metropolis",
        "origin_region": "Global",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/modern_architecture_v1.safetensors", "scale": 0.85, "trigger": "modern architecture, glass skyscraper, brutalist concrete, blue hour skyline"},
        "prompt_decorations": "contemporary architectural marvel, soaring curvilinear glass and steel skyscrapers, cantilevered brutalist concrete, reflective water mirrors, blue-hour metropolitan skyline, 8K architectural photography",
        "lighting_scheme": "Crisp twilight blue-hour with warm interior architectural illumination, sleek reflections on glass facades",
        "color_palette": "Cool architectural steel, deep twilight blue, polished glass cyan, warm ambient amber, pure white",
        "directorial_guidance": "Geometric symmetry, vertical low-angle tilts revealing soaring height, slow linear dolly tracking, ambient sound design.",
        "music_style": "Sophisticated ambient neoclassical and minimalist electronic score with deep resonant sub-bass and warm synth pads",
        "architecture_style": "Contemporary curvilinear glass curtain walls, cantilevered structural steel, geometric brutalist forms, and sleek public plazas",
    },
    "photorealistic_cinematic": {
        "display_name": "Broadcast 4K Photorealistic Cinematic",
        "origin_country": "Global",
        "origin_region": "Global",
        "recommended_diffusion_model": "flux-1-dev",
        "prompt_decorations": "Raw 35mm film photograph, Arri Alexa 35mm Master Prime lens, natural human skin texture with visible micro-pores and subtle perspiration, authentic skin tones, organic film grain, natural daylight, zero airbrushed plastic, zero CGI sheen",
        "lighting_scheme": "Cinematic balanced daylight with natural ambient fill, realistic specular highlights, and true skin tones",
        "color_palette": "Natural organic film grading, true-to-life skin tones, rich earthy tones, high dynamic range",
        "directorial_guidance": "Engaging broadcast storytelling, crisp narrative arc, clear emotional beats, and authentic visual fidelity.",
        "music_style": "Cinematic orchestral score with dynamic emotional pacing",
        "architecture_style": "Contemporary cinematic locations with pristine architectural and environmental authenticity",
    },
    "miami_tropical_rain_storm": {
        "display_name": "Downtown Miami Tropical Thunderstorm & Rain Walk",
        "origin_country": "United States",
        "origin_region": "North America",
        "recommended_diffusion_model": "flux-1-dev",
        "recommended_lora": {"path": "loras/miami_storm_v1.safetensors", "scale": 0.85, "trigger": "miami thunderstorm, flooded streets, palm trees in rain, reflective wet asphalt, neon reflections"},
        "prompt_decorations": "Downtown Miami and Brickell avenue, torrential tropical thunderstorm rain, swaying palm trees drenched in rain, water-sheeted flooded asphalt streets with brilliant reflections of modern glass high-rises and neon signage, distant lightning flash, 4K walking tour POV",
        "lighting_scheme": "Atmospheric tropical storm twilight with dramatic lightning flashes, neon storefront glows, and glistening pavement water reflections",
        "color_palette": "Deep storm teal, palm emerald green, glistening asphalt charcoal, neon amber, lightning white",
        "directorial_guidance": "Ultra-slow tranquil first-person walking tour, steadycam forward glide at 1.5-2.0 km/h, immersive binaural rain and thunder ASMR.",
        "music_style": "Atmospheric cinematic chillout with high-fidelity binaural recordings of tropical downpour, rolling thunder, and rain on palm leaves",
        "architecture_style": "Contemporary Miami glass high-rises, coastal palm boulevards, art deco and modern architectural streetscapes",
    },
}
